### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Shadow-Master** [rdeits/WPepub#1]
I did a quick pull and installed dependencies. All seem to be working an import correctly when I open them in a python shell, yet when I do a rake, here's the output:

 ~/WPepub
$ rake
python scrape.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   1058      0 --:--:-- --:--:-- --:--:--  1186
Traceback (most recent call last):
  File "scrape.py", line 29, in <module>
    WP_scrape()
  File "scrape.py", line 13, in WP_scrape
    categories = soup.find_all(attrs={"class":"widget_categories"})[0]
IndexError: list index out of range
rake aborted!

Any thoughts? I don't know enough python to have a crack at it.

**Comment by mfeyg** [comment]
Using HTTPS solves this issue. See https://github.com/rdeits/WPepub/pull/2.

**Comment by rdeits** [comment]
thanks, @mfeyg !
